# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-05 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_paint_paint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paint',
            name='author',
        ),
        migrations.AlterField(
            model_name='paint',
            name='paint',
            field=models.ImageField(blank=True, null=True, upload_to='/book_paint/portfolio/static/img/paint'),
        ),
    ]
